### 1. Registrar admin
POST {{base_url}}/api/v1/auth/register
Content-Type: application/json

{
  "email": "{{admin_email}}",
  "password": "{{admin_password}}"
}

### 2. Login admin
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "{{admin_email}}",
  "password": "{{admin_password}}"
}

> {% client.global.set("access_token", response.body.accessToken) %}

###

# ================== ADMIN CRUD ==================

### 3. Crear provider
POST http://localhost:8080/api/v1/admin/providers
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "providerName": "mangadex",
  "providedLang": "en",
  "logoUrl": "https://logo.url/mangadex.png"
}

> {% client.global.set("provider_id", respons %}

### 4. Crear manga
POST http://localhost:8080/api/v1/admin/mangas
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "title": "Berserk",
  "author": "Kentaro Miura",
  "description": "Un héroe que derrota a todos de un solo golpe.",
  "coverUrl": "https://cover.url/opm.jpg",
  "faviconUrl": "https://favicon.url/opm.png"
}

> {% client.global.set("manga_id", response.body.id) %}

### 5. Crear volumen
POST http://localhost:8080/api/v1/admin/mangas/{{manga_id}}/volumes
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "volumeNumber": 1,
  "title": "Volumen 1",
  "coverUrl": "https://cover.url/vol1.jpg"
}

> {% client.global.set("volume_id", response.body.id) %}

### 6. Crear capítulo
POST http://localhost:8080/api/v1/admin/volumes/{{volume_id}}/chapters
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "chapterNumber": "1",
  "title": "Capítulo 1"
}

> {% client.global.set("chapter_id", response.body.id) %}

### 7. Crear chapter-source
POST http://localhost:8080/api/v1/admin/chapter-sources
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "chapterId": "{{chapter_id}}",
  "providerId": "{{provider_id}}",
  "languageCode": "en"
}

> {% client.global.set("chapter_source_id", response.body.id) %}

### 8. Crear página
POST http://localhost:8080/api/v1/admin/pages/{{chapter_source_id}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "pageNumber": 1,
  "imageUrl": "https://manga.page/1.jpg"
}

###

# ============= CLIENT =================

### 9. Registrar usuario cliente
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "email": "{{client_email}}",
  "password": "{{client_password}}"
}


### 10. Login cliente
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "{{client_email}}",
  "password": "{{client_password}}"
}

> {% client.global.set("client_token", response.body.accessToken) %}

### 11. Leer capítulo (simula lectura y actualiza historial)
GET http://localhost:8080/api/v1/public/pages/by-chapter/{{chapter_id}}?lang=en
Authorization: Bearer {{client_token}}

###

### 12. Dar me gusta (registra favorito)
POST http://localhost:8080/api/v1/me/likes/{{manga_id}}
Authorization: Bearer {{client_token}}

###

### 13. Obtener contexto del usuario
GET http://localhost:8080/api/v1/me/context
Authorization: Bearer {{client_token}}



### 14. Ver preferencias del usuario
GET http://localhost:8080/api/v1/me/context/preferences
Authorization: Bearer {{client_token}}

###

### 15. Editar preferencias del usuario
PUT http://localhost:8080/api/v1/me/context/preferences
Authorization: Bearer {{client_token}}
Content-Type: application/json

{
  "theme": "dark",
  "readingDirection": "rtl",
  "defaultProvider": "mangadex"
}
Este tiene un erro ya que las prefencias estan en null, error de inciializacion.
###

### 16. Obtener última lectura
GET http://localhost:8080/api/v1/me/context/last-read
Authorization: Bearer {{client_token}}

###

### 17. Obtener historial completo
GET http://localhost:8080/api/v1/me/context/history
Authorization: Bearer {{client_token}}

###

### 18. Ver comentarios de un manga
GET http://localhost:8080/api/v1/comments/{{manga_id}}/
Authorization: Bearer {{client_token}}